version: '3'
services:
  xzy-nginx:
    restart: always
    container_name: xzy-nginx
    volumes:
      - /data/nginx:/etc/nginx/
    image: nginx:1.19.3-alpine
    ports:
      - 80:80
  xzy-tomcat1:
    restart: always
    container_name: xzy-tomcat1
    volumes:
      - /data/tomcat1/webapps:/usr/local/tomcat/webapps
    image: tomcat:9.0.20-jre8-alpine
    ports:
      - 8081:8080
    depends_on:
      - xzy-nginx
  xzy-tomcat2:
    restart: always
    container_name: xzy-tomcat2
    volumes:
      - /data/tomcat2/webapps:/usr/local/tomcat/webapps
    image: tomcat:9.0.20-jre8-alpine
    ports:
      - 8082:8080
    depends_on:
      - xzy-nginx